-- if CLIENT then return end
--
--
--
-- hook.Add("Think", "bleghhhhh", function()
-- for k, v in pairs (ents.FindByClass ("prop_physics") ) do
--
--
-- litprop = v
--
-- end
--
--
--         local lo = jazztardis.metadata.Interior.LightOverride
--         local lob = jazztardis:GetPower() and lo.basebrightness or lo.nopowerbrightness
--
--         local lobc = Color(lob, lob, lob)
--
-- local lobcvec = lobc:ToVector()
--
-- --   litprop:SetLightingOriginEntity( jazztardis )
--
--
-- end)



-- hook.Add("PlayerSpawnedEffect", "bleghhhhh", function(ply, mdl, ent)
--
-- local vang = ent:GetAngles()
--
-- vang:RotateAroundAxis(Vector (0,1,1),90 )
--     ent:SetAngles( vang )
-- end)
